package util;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 19:10:36 GMT 2020
 */

import java.util.Map;
import org.jgrapht.nio.Attribute;
import org.jgrapht.nio.DefaultAttribute;
 
public class RelationshipWeightedEdgeTest {

  @Test
  public void test00()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("&TU%gym");
      relationshipWeightedEdge0.setAttrs((Map<String, Attribute>) null);
      Map<String, Attribute> map0 = relationshipWeightedEdge0.getAtts();
      assertNull(map0);
  }

  @Test
  public void test01()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      Map<String, Attribute> map0 = relationshipWeightedEdge0.getAtts();
      assertEquals(0, map0.size());
  }

  @Test
  public void test02()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("a)dACYpbUC&RX");
      Double double0 = Double.valueOf(29.98929);
      Attribute attribute0 = DefaultAttribute.createAttribute(double0);
      relationshipWeightedEdge0.setAtt("", attribute0);
      Object object0 = relationshipWeightedEdge0.getAtt("");
      assertSame(object0, attribute0);
  }

  @Test
  public void test03()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("");
      RelationshipWeightedEdge relationshipWeightedEdge1 = new RelationshipWeightedEdge("S#6=h(vu4+9");
      boolean boolean0 = relationshipWeightedEdge0.equals(relationshipWeightedEdge1);
      assertFalse(boolean0);
  }

  @Test
  public void test04()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("T g");
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.toStringAtt();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         ////verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test
  public void test05()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("&TU%gym");
      relationshipWeightedEdge0.setAttrs((Map<String, Attribute>) null);
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test06()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      relationshipWeightedEdge0.setAttrs((Map<String, Attribute>) null);
      Attribute attribute0 = DefaultAttribute.createAttribute((Boolean) null);
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.setAtt((String) null, attribute0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         ////verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test07()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.getNeighbor((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         ////verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test08()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("U7!>rAL8>J~rI");
      relationshipWeightedEdge0.setAttrs((Map<String, Attribute>) null);
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.getLabel();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test09()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      relationshipWeightedEdge0.setAttrs((Map<String, Attribute>) null);
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.getAtt("{null,null}");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test10()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("");
      // Undeclared exception!
      try { 
        relationshipWeightedEdge0.equals((RelationshipWeightedEdge) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //verifyException("util.RelationshipWeightedEdge", e);
      }
  }

  @Test
  public void test11()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      String string0 = relationshipWeightedEdge0.getLabel();
      assertEquals("{null,null}", string0);
  }

  @Test
  public void test12()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("T g");
      String string0 = relationshipWeightedEdge0.getLabel();
      assertNotNull(string0);
  }

  @Test
  public void test13()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      String string0 = relationshipWeightedEdge0.toString();
      assertEquals("{null,null}", string0);
  }

  @Test
  public void test14()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("T g");
      String string0 = relationshipWeightedEdge0.toString();
      assertNotNull(string0);
  }

  @Test
  public void test15()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      relationshipWeightedEdge0.hashCode();
  }

  @Test
  public void test16()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      Boolean boolean0 = Boolean.valueOf("3u6`?poMG=I?J");
      Attribute attribute0 = DefaultAttribute.createAttribute(boolean0);
      Object object0 = relationshipWeightedEdge0.getNeighbor(attribute0);
      assertNull(object0);
  }

  @Test
  public void test17()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      boolean boolean0 = relationshipWeightedEdge0.equals(relationshipWeightedEdge0);
      assertTrue(boolean0);
  }

  @Test
  public void test18()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      Object object0 = relationshipWeightedEdge0.getAtt("");
      assertNull(object0);
  }

  @Test
  public void test19()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge();
      Object object0 = relationshipWeightedEdge0.getV1();
      assertNull(object0);
  }

  @Test
  public void test20()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("T g");
      Object object0 = relationshipWeightedEdge0.getV2();
      assertNull(object0);
  }

  @Test
  public void test21()  throws Throwable  {
      RelationshipWeightedEdge relationshipWeightedEdge0 = new RelationshipWeightedEdge("");
      Map<String, Attribute> map0 = relationshipWeightedEdge0.getAtts();
      relationshipWeightedEdge0.setAttrs(map0);
      assertFalse(map0.isEmpty());
  }
}
